from datetime import date


class ReportGenerator:
    def generate_summary(self, score: int, category: str, keyword_results: dict) -> str:
        matched_count = len(keyword_results.get('matched', []))
        missing_count = len(keyword_results.get('missing', []))
        total = keyword_results.get('total_jd', 0)

        summary = (
            f"Your resume matches {score}% of the job description keywords ({category}). "
            f"You matched {matched_count} out of {total} key terms. "
        )
        if missing_count:
            summary += (
                f"Consider adding {missing_count} missing keyword(s) to improve your ATS score."
            )
        else:
            summary += "Great job — no critical keywords are missing!"
        return summary

    def generate_markdown(self, data: dict) -> str:
        today = date.today().strftime('%B %d, %Y')
        score = data.get('ats_score', 0)
        category = data.get('score_category', '')
        matched = data.get('matched_keywords', [])
        missing = data.get('missing_keywords', [])
        suggestions = data.get('action_words_analysis', {}).get('suggestions', [])
        summary = data.get('summary', '')

        lines = [
            f"# Resume Optimization Report",
            f"**Date:** {today}",
            f"",
            f"## ATS Score: {score}% — {category}",
            f"",
            f"### Summary",
            summary,
            f"",
            f"---",
            f"",
            f"## Matched Keywords ({len(matched)})",
            ', '.join(matched) if matched else '_None_',
            f"",
            f"## Missing Keywords ({len(missing)})",
            ', '.join(missing) if missing else '_None — great match!_',
            f"",
        ]

        if suggestions:
            lines += [
                f"## Action Word Improvements",
                '',
            ]
            for s in suggestions:
                lines.append(f"- Replace **{s['current']}** → **{s['suggested']}**")
            lines.append('')

        lines += [
            f"---",
            f"",
            f"## Recommendations",
            f"",
        ]

        if missing:
            lines.append(f"- Add these missing keywords naturally into your resume: {', '.join(missing[:5])}")
        if suggestions:
            lines.append(f"- Strengthen your action verbs using the suggestions above.")
        if score < 50:
            lines.append(f"- Your resume needs significant keyword alignment. Review the job description carefully.")
        elif score < 75:
            lines.append(f"- You're on the right track. A few more keyword additions will boost your score.")
        else:
            lines.append(f"- Strong match! Focus on tailoring your experience descriptions.")

        lines += [
            f"",
            f"---",
            f"_Generated by Resume Optimizer_",
        ]

        return '\n'.join(lines)
